version:  '3'
services:
    template:
        container_name: template
        build:
            context: template-conversion
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        tty: true
        command: python3 src/main.py

    main:
        container_name: main
        build: .
        tty: true
        links:
            - template
        volumes:
            - ./config/:/config/
        command: sleep 10;python3 src/main.py
